/**
 * Build the final project report as a .docx.
 *
 * Every figure is generated by the project's own code and every screenshot is
 * captured from a live system. Nothing is mocked.
 */

const fs = require("fs");
const path = require("path");
const {
  AlignmentType, BorderStyle, Document, Footer, Header, HeadingLevel, ImageRun,
  LevelFormat, PageBreak, PageNumber, Packer, Paragraph, ShadingType, Table,
  TableCell, TableRow, TabStopType, TextRun, TableOfContents, VerticalAlign,
  WidthType,
} = require("docx");

const ROOT = "/Users/krishnamathurm4pro/Desktop/Academics/SDIAM Term 3/SDAIM FINAL PROJECT";
const FIG = path.join(ROOT, "reports", "figures");
const SHOT = path.join(ROOT, "docs", "screenshots");
const OUT = path.join(ROOT, "Customer_Churn_Intelligence_Final_Report.docx");

// US Letter, 1 inch margins -> 6.5in usable = 624px at 96dpi.
const PAGE_W = 12240, PAGE_H = 15840, MARGIN = 1440;
const CONTENT_PX = 620;
const TABLE_W = 9360; // 6.5in in DXA

const NAVY = "1E3A8A", INK = "0F172A", MUTED = "475569";
const RULE = "D7DFEC", HEADBG = "EEF3FB", ALTBG = "F7F9FC";

let figureCounter = 0;
let tableCounter = 0;

/** Read intrinsic PNG dimensions from the IHDR chunk. */
function pngSize(file) {
  const buf = fs.readFileSync(file);
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

function imageParagraph(file, maxWidth = CONTENT_PX) {
  const { width, height } = pngSize(file);
  const w = Math.min(maxWidth, width);
  const h = Math.round((height / width) * w);
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 160, after: 60 },
    children: [
      new ImageRun({
        type: "png",
        data: fs.readFileSync(file),
        transformation: { width: w, height: h },
      }),
    ],
  });
}

function caption(text, kind = "Figure") {
  const n = kind === "Figure" ? ++figureCounter : ++tableCounter;
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 240 },
    children: [
      new TextRun({ text: `${kind} ${n}. `, bold: true, size: 17, color: NAVY }),
      new TextRun({ text, size: 17, italics: true, color: MUTED }),
    ],
  });
}

function figure(file, text, maxWidth) {
  return [imageParagraph(file, maxWidth), caption(text, "Figure")];
}

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 360, after: 180 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: NAVY, space: 6 } },
    children: [new TextRun({ text, bold: true, size: 30, color: NAVY })],
  });
}

function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 140 },
    children: [new TextRun({ text, bold: true, size: 25, color: INK })],
  });
}

function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 220, after: 110 },
    children: [new TextRun({ text, bold: true, size: 22, color: MUTED })],
  });
}

/** Body paragraph. Accepts a string, or an array of {t, b, i, code} runs. */
function p(content, opts = {}) {
  const runs = (typeof content === "string" ? [{ t: content }] : content).map(
    (r) =>
      new TextRun({
        text: r.t,
        bold: !!r.b,
        italics: !!r.i,
        size: 21,
        color: r.color || INK,
        font: r.code ? "Consolas" : undefined,
      })
  );
  return new Paragraph({
    spacing: { after: opts.after ?? 140, line: 300 },
    alignment: opts.align || AlignmentType.LEFT,
    children: runs,
  });
}

function bullet(content, level = 0) {
  const runs = (typeof content === "string" ? [{ t: content }] : content).map(
    (r) =>
      new TextRun({
        text: r.t, bold: !!r.b, italics: !!r.i, size: 21,
        color: r.color || INK, font: r.code ? "Consolas" : undefined,
      })
  );
  return new Paragraph({
    numbering: { reference: "bullets", level },
    spacing: { after: 70, line: 290 },
    children: runs,
  });
}

function numbered(content, level = 0) {
  const runs = (typeof content === "string" ? [{ t: content }] : content).map(
    (r) => new TextRun({ text: r.t, bold: !!r.b, italics: !!r.i, size: 21,
                         color: r.color || INK, font: r.code ? "Consolas" : undefined })
  );
  return new Paragraph({
    numbering: { reference: "numbers", level },
    spacing: { after: 70, line: 290 },
    children: runs,
  });
}

function code(lines) {
  return new Paragraph({
    spacing: { before: 120, after: 160 },
    shading: { type: ShadingType.CLEAR, fill: "F4F6FA" },
    border: {
      left: { style: BorderStyle.SINGLE, size: 12, color: NAVY, space: 8 },
      top: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 4 },
      bottom: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 4 },
      right: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 4 },
    },
    children: lines.flatMap((line, i) => [
      ...(i ? [new TextRun({ break: 1 })] : []),
      new TextRun({ text: line, font: "Consolas", size: 17, color: INK }),
    ]),
  });
}

function callout(title, body, accent = "B45309") {
  return new Paragraph({
    spacing: { before: 160, after: 200, line: 290 },
    shading: { type: ShadingType.CLEAR, fill: "FBF7EF" },
    border: {
      left: { style: BorderStyle.SINGLE, size: 18, color: accent, space: 10 },
      top: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 6 },
      bottom: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 6 },
      right: { style: BorderStyle.SINGLE, size: 2, color: RULE, space: 6 },
    },
    children: [
      new TextRun({ text: `${title} `, bold: true, size: 20, color: accent }),
      new TextRun({ text: body, size: 20, color: INK }),
    ],
  });
}

/** Table from a header row plus body rows. `align` is per-column: 'l' | 'r'. */
function table(header, rows, widths, align = null) {
  const total = widths.reduce((a, b) => a + b, 0);
  const cols = widths.map((w) => Math.round((w / total) * TABLE_W));
  const alignment = align || header.map(() => "l");

  const cell = (text, i, isHeader, zebra) =>
    new TableCell({
      width: { size: cols[i], type: WidthType.DXA },
      shading: { type: ShadingType.CLEAR, fill: isHeader ? HEADBG : zebra ? ALTBG : "FFFFFF" },
      margins: { top: 70, bottom: 70, left: 90, right: 90 },
      verticalAlign: VerticalAlign.CENTER,
      children: [
        new Paragraph({
          alignment: alignment[i] === "r" ? AlignmentType.RIGHT : AlignmentType.LEFT,
          spacing: { after: 0, line: 260 },
          children: String(text).split("\n").flatMap((part, k) => [
            ...(k ? [new TextRun({ break: 1 })] : []),
            new TextRun({
              text: part, bold: isHeader, size: 18,
              color: isHeader ? NAVY : INK,
            }),
          ]),
        }),
      ],
    });

  return new Table({
    width: { size: TABLE_W, type: WidthType.DXA },
    columnWidths: cols,
    rows: [
      new TableRow({
        tableHeader: true,
        children: header.map((t, i) => cell(t, i, true, false)),
      }),
      ...rows.map((r, ri) =>
        new TableRow({ children: r.map((t, i) => cell(t, i, false, ri % 2 === 1)) })
      ),
    ],
  });
}

function spacer(after = 160) {
  return new Paragraph({ spacing: { after }, children: [] });
}

function pageBreak() {
  return new Paragraph({ children: [new PageBreak()] });
}

const S = (name) => path.join(SHOT, name);
const F = (name) => path.join(FIG, name);

// ===========================================================================
// Document content
// ===========================================================================

const children = [];

// ---------------------------------------------------------------- COVER ----
children.push(
  new Paragraph({ spacing: { before: 1400, after: 0 }, children: [] }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
    children: [new TextRun({
      text: "CUSTOMER CHURN INTELLIGENCE",
      bold: true, size: 52, color: NAVY,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 260 },
    children: [new TextRun({
      text: "and Retention Decision-Support Platform",
      size: 34, color: INK,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 500 },
    border: { top: { style: BorderStyle.SINGLE, size: 8, color: NAVY, space: 14 } },
    children: [new TextRun({
      text: "End-to-End Machine Learning Model Deployment using Hugging Face and GitHub Actions",
      italics: true, size: 23, color: MUTED,
    })],
  }),
);

children.push(
  table(
    ["Field", "Detail"],
    [
      ["Module", "SDAIM — Term 3"],
      ["Instructor", "JP Aggarwal"],
      ["Team members", "Krishna Mathur (AS25DXB018)\nYash Petkar (AS25DXB021)\nAtharva Soundankar (AS25DXB020)"],
      ["GitHub repository", "https://github.com/krish2105/SDAIM-Customer-Churn"],
      ["Hugging Face Space", "https://huggingface.co/spaces/krish21may/churn"],
      ["Live application", "https://krish21may-churn.hf.space"],
      ["Application version", "1.1.0"],
      ["Deployment status", "Live — built, running and verified"],
    ],
    [30, 70]
  )
);

children.push(
  spacer(500),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({
      text: "All metrics in this report were produced by the project's own code. All screenshots were captured from live, running systems.",
      italics: true, size: 18, color: MUTED,
    })],
  }),
  pageBreak()
);

// ------------------------------------------------------------------ TOC ----
children.push(
  h1("Table of Contents"),
  new TableOfContents("Contents", { hyperlink: true, headingStyleRange: "1-3" }),
  pageBreak()
);

// ------------------------------------------------------ EXEC SUMMARY -------
children.push(
  h1("Executive Summary"),
  p([
    { t: "This project delivers a working customer-retention decision-support platform: a validated dataset, a leakage-safe machine-learning pipeline, an interactive Streamlit application, Docker packaging, and fully automated deployment to a public Hugging Face Space through GitHub Actions. " },
    { t: "Every component has been built, tested and deployed. The application is live and can be used now.", b: true },
  ]),
  p([
    { t: "The selected model — Logistic Regression inside a complete scikit-learn pipeline — achieves " },
    { t: "0.8414 ROC-AUC", b: true },
    { t: " and " },
    { t: "0.7834 recall", b: true },
    { t: " on a held-out test set of 1,409 customers that no model saw during fitting or selection. It identifies 293 of the 374 actual churners in that set and misses 81." },
  ]),
  p("Recall is weighted deliberately. A missed churner receives no retention review at all, and the opportunity to intervene is lost silently. An unnecessary review costs a specialist's time and is recoverable. The two errors are not equal, and the model is tuned for the one that matters."),
  h2("What distinguishes this submission"),
  bullet([{ t: "Provenance is proven, not asserted. ", b: true }, { t: "The dataset's Git blob SHA is verified against the official IBM publication on every run, in local development and in continuous integration." }]),
  bullet([{ t: "The model selection rule was fixed in code before the test set was examined. ", b: true }, { t: "This is what makes the held-out evaluation genuinely unbiased." }]),
  bullet([{ t: "A fairness audit was performed, with a measured counterfactual. ", b: true }, { t: "Removing the protected attributes was found to cost only +0.0008 ROC-AUC, which changed the recommendation." }]),
  bullet([{ t: "Calibration was predicted, then measured. ", b: true }, { t: "The model was expected to be over-confident because of balanced class weights; it is, by 0.15." }]),
  bullet([{ t: "Feature engineering and hyperparameter search were tried and rejected on the evidence. ", b: true }, { t: "The best gain was +0.0022 against a pre-declared bar of 0.005." }]),
  bullet([{ t: "115 automated tests", b: true }, { t: " and ten local quality gates, all passing." }]),
  callout(
    "Scope of claims.",
    "The dataset is IBM's fictional telecommunications sample. This platform demonstrates technical feasibility and may support prioritisation of accounts for human review. No revenue, churn-reduction or return-on-investment effect has been measured, and none is claimed anywhere in this report.",
    "B45309"
  ),
  pageBreak()
);

// ============================== 1. PROBLEM STATEMENT =======================
children.push(
  h1("1. Problem Statement and Business Objective"),
  h2("1.1 The business problem"),
  p("A telecommunications organisation loses customers continuously, but its retention specialists have finite time. Without a consistent basis for deciding which accounts deserve attention, prioritisation falls to individual judgement: inconsistent between specialists, undocumented, and impossible to audit or improve."),
  p("The organisation does not need a system that decides what to do about a customer. It needs a repeatable, documented estimate of which accounts are at elevated risk, so that a human being can review the right ones first."),
  h2("1.2 The decision this platform supports"),
  p([{ t: "Decision supported: ", b: true }, { t: "prioritising customer accounts for a structured human retention review." }]),
  p([{ t: "Explicitly not supported: ", b: true }, { t: "changing prices, modifying or terminating contracts, denying or degrading service, or making any automated customer-treatment decision." }]),
  h2("1.3 Stakeholders"),
  table(
    ["Stakeholder", "Interest in this platform"],
    [
      ["Chief Customer Officer", "Consistency and defensibility of retention prioritisation"],
      ["Chief Marketing Officer", "Targeting efficiency of retention activity"],
      ["Retention leadership", "A bounded, prioritised review workload"],
      ["Customer-service managers", "Practical account-level guidance"],
      ["Data and analytics", "Reproducibility and maintainability"],
      ["Model risk and governance", "Documented limitations and human-review controls"],
    ],
    [32, 68]
  ),
  spacer(),
  h2("1.4 Required outputs"),
  p("For a single customer record the platform returns a predicted churn class, a churn probability, a Low / Medium / High risk band, a cautiously worded suggested review action, the model version, and an explicit statement of the model's limitations."),
  h2("1.5 Governance boundary"),
  callout(
    "Human review is mandatory.",
    "Every output of this model requires human review before any customer is contacted. The model has no authority to act, and no downstream system consumes its output as an automated trigger. This constraint appears in the model card, on screen in the application, and in this report because it is a design property, not a disclaimer.",
    "B4232B"
  ),
  pageBreak()
);

// ============================== 2. DATASET =================================
children.push(
  h1("2. Dataset Description and Source"),
  h2("2.1 Source and provenance"),
  table(
    ["Property", "Value"],
    [
      ["Dataset", "IBM Telco Customer Churn sample"],
      ["Publisher", "IBM"],
      ["Official repository", "https://github.com/IBM/telco-customer-churn-on-icp4d"],
      ["Licence", "Apache-2.0"],
      ["Records", "7,043 customers"],
      ["Columns", "21"],
      ["Target variable", "Churn (Yes / No)"],
      ["Identifier excluded from modelling", "customerID"],
      ["Verified Git blob SHA", "3de7a612d1609f25f21a455bda77948729369002"],
      ["SHA-256 (informational)", "16320c9c1ec72448db59aa0a26a0b95401046bef5d02fd3aeb906448e3055e91"],
    ],
    [34, 66]
  ),
  spacer(),
  h2("2.2 Why the dataset was chosen"),
  p("The problem is a binary classification task with a clear business decision attached, a well-defined target, and enough records and features for meaningful analysis. The dataset is officially published, permissively licensed, and — critically — verifiable: its exact revision can be proven rather than assumed."),
  h2("2.3 Fictional-data disclosure"),
  callout(
    "Important.",
    "The IBM sample represents a fictional telecommunications company. It is realistic in structure and officially published, but it is not actual observed commercial customer data, and it is never described as such anywhere in this project. The brief asks for a real-world dataset; this point was raised with the instructor and is recorded as pending confirmation in PROJECT_INPUTS.md and as decision D-01 in DECISIONS.md.",
    "B45309"
  ),
  h2("2.4 Integrity verification"),
  p("The raw file is treated as immutable evidence. It is never written to, and its identity is proven on every run rather than trusted:"),
  code([
    "$ git hash-object data/raw/Telco-Customer-Churn.csv",
    "3de7a612d1609f25f21a455bda77948729369002",
    "",
    "$ make validate",
    "Rows / columns  : 7043 / 21",
    "Git blob SHA    : 3de7a612d1609f25f21a455bda77948729369002",
    "Expected SHA    : 3de7a612d1609f25f21a455bda77948729369002",
    "Target counts   : {'No': 5174, 'Yes': 1869}",
    "Checks executed : 30",
    "RESULT          : PASSED",
  ]),
  p("Thirty automated checks cover column names and order, row count, identifier uniqueness, target and category domains, numeric convertibility, impossible negative values, blank-value counts and the blob SHA. Continuous integration runs the validator with --strict-sha, so a missing or altered dataset fails the build rather than producing quietly different results."),
  h2("2.5 Features"),
  p("Nineteen predictors are used: sixteen categorical and three numeric. The identifier is excluded entirely."),
  table(
    ["Group", "Features"],
    [
      ["Customer profile", "gender, SeniorCitizen, Partner, Dependents"],
      ["Services", "PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies"],
      ["Contract and billing", "Contract, PaperlessBilling, PaymentMethod"],
      ["Charges and tenure", "tenure, MonthlyCharges, TotalCharges"],
    ],
    [26, 74]
  ),
  spacer(),
  p([
    { t: "SeniorCitizen", code: true },
    { t: " is encoded 0/1 but is a binary flag, not a magnitude, so it is treated as a category. Scaling it as a number would imply an ordering and a distance that do not exist." },
  ]),
  pageBreak()
);

// ============================== 3. EDA =====================================
children.push(
  h1("3. Exploratory Data Analysis and Key Observations"),
  p([
    { t: "Every figure and number in this section is produced by " },
    { t: "src/eda.py", code: true },
    { t: " from the validated raw file. None was entered by hand. The script is the single source of truth; the accompanying notebook imports the same functions rather than duplicating the logic, so the two cannot disagree." },
  ]),
  h2("3.1 Target balance"),
  ...figure(F("01_target_distribution.png"), "Target class distribution. 1,869 customers churned (26.54%) against 5,174 retained.", 430),
  p([
    { t: "The sample contains 26.54% churners. This single fact drives the entire evaluation strategy: a model that predicted \"retained\" for every customer would score " },
    { t: "73.46% accuracy while identifying nobody at risk", b: true },
    { t: ". Accuracy alone is therefore not an acceptable selection metric, and recall, F1 and ROC-AUC are used instead." },
  ]),
  h2("3.2 Data quality"),
  p("After stripping whitespace and coercing TotalCharges to numeric, exactly 11 values are missing across the entire table — all in TotalCharges, and all belonging to customers with tenure = 0. These are people who have not yet completed a billing cycle. The blank is structurally meaningful rather than random, which is why the rows are retained rather than dropped."),
  ...figure(F("02_missing_values.png"), "Missing values after coercion. All 11 are in TotalCharges and all have tenure = 0.", 430),
  p("There are no duplicate rows and no duplicate customerID values. No numeric field contains a negative value. All sixteen categorical fields match the domains in the IBM data dictionary exactly."),
  h2("3.3 Contract term is the strongest categorical signal"),
  ...figure(F("06_churn_rate_by_contract.png"), "Churn rate by contract term. Month-to-month customers churn at more than fifteen times the two-year rate.", 460),
  table(
    ["Contract term", "Customers", "Churn rate"],
    [["Month-to-month", "3,875", "42.71%"], ["One year", "1,473", "11.27%"], ["Two year", "1,695", "2.83%"]],
    [40, 30, 30], ["l", "r", "r"]
  ),
  spacer(),
  h2("3.4 Payment method and internet service"),
  ...figure(F("08_churn_rate_by_paymentmethod.png"), "Churn rate by payment method. Electronic check customers churn at nearly three times the automatic-credit-card rate.", 460),
  ...figure(F("07_churn_rate_by_internetservice.png"), "Churn rate by internet service. Fibre optic customers churn at 41.89% against 7.40% for customers with no internet service.", 440),
  h2("3.5 Tenure"),
  ...figure(F("03_tenure_by_churn.png"), "Tenure distribution by churn status. Churn concentrates sharply among recently acquired customers.", 450),
  p("Churned customers average 17.98 months of tenure against 37.57 months for retained customers. Median tenure is 10 months for churners and 38 for non-churners. Early-life accounts carry materially higher risk."),
  h2("3.6 Numeric correlations"),
  ...figure(F("11_correlation_matrix.png"), "Pearson correlation between the numeric predictors and the binary churn flag.", 400),
  p("Tenure correlates with the churn flag at −0.352, MonthlyCharges at +0.193 and TotalCharges at −0.200. Tenure and TotalCharges correlate strongly with each other at 0.826, which is expected because total charges accumulate with time. This is recorded as a known limitation: the tree ensemble tolerates it, and the linear model relies on scaling and regularisation."),
  h2("3.7 Key observations carried into modelling"),
  numbered("Class imbalance means recall and ROC-AUC drive model selection, not accuracy."),
  numbered("TotalCharges requires coercion and in-pipeline imputation; the raw file stays untouched."),
  numbered("SeniorCitizen is a binary category, not a continuous magnitude."),
  numbered("customerID is excluded from the feature set entirely."),
  numbered("Contract term, internet service, tenure and payment method are the strongest observed signals and are all retained."),
  callout(
    "Association, not causation.",
    "Every relationship described above is an association within a fictional sample. None is evidence of cause. The service add-on comparisons are additionally confounded, because the level \"No internet service\" appears in every add-on column and therefore partly restates the internet-service split.",
    "1E40AF"
  ),
  pageBreak()
);

// ============================== 4. PREPROCESSING ===========================
children.push(
  h1("4. Data Preprocessing"),
  h2("4.1 Steps applied"),
  numbered([{ t: "Type correction. ", b: true }, { t: "TotalCharges is stripped of whitespace and coerced with errors=\"coerce\"; tenure and MonthlyCharges are cast to numeric." }]),
  numbered([{ t: "Target mapping. ", b: true }, { t: "Churn is mapped Yes to 1 and No to 0, outside the feature matrix." }]),
  numbered([{ t: "Identifier exclusion. ", b: true }, { t: "customerID is dropped before X is constructed. Two assertions in the code make this impossible to undo by accident." }]),
  numbered([{ t: "Type discipline. ", b: true }, { t: "SeniorCitizen is cast to string so it routes through the categorical branch." }]),
  numbered([{ t: "Single stratified split. ", b: true }, { t: "80/20, random_state=42, performed once — before any transformer exists." }]),
  numbered([{ t: "Numeric branch. ", b: true }, { t: "Median imputation, plus standard scaling for the linear model only." }]),
  numbered([{ t: "Categorical branch. ", b: true }, { t: "Most-frequent imputation, then one-hot encoding with handle_unknown=\"ignore\"." }]),
  numbered([{ t: "Single pipeline. ", b: true }, { t: "Preprocessing and estimator are combined into one scikit-learn Pipeline and saved as one artifact." }]),
  h2("4.2 Data-leakage prevention"),
  p([
    { t: "The leakage control in this project is ", },
    { t: "structural rather than procedural", b: true },
    { t: ". It does not depend on anyone remembering to do things in the right order." },
  ]),
  bullet("The split happens once, before any imputer, encoder or scaler is instantiated."),
  bullet("Every transformer lives inside the Pipeline, so cross-validation refits each of them from scratch on every fold. No statistic computed on held-out rows can reach a fitted parameter."),
  bullet("The held-out test set is used exactly once, after model selection is complete."),
  bullet("Stratification preserves the class balance: the positive rate is 0.2654 in both the training and test splits."),
  callout(
    "The concrete mistake this prevents.",
    "Imputing the 11 missing TotalCharges values before splitting would compute the median using test-set rows. The model would then have been tuned against information it will not have in production, and every reported metric would be optimistic by an unknown amount.",
    "1E40AF"
  ),
  h2("4.3 Handling unseen categories at inference"),
  p([
    { t: "OneHotEncoder(handle_unknown=\"ignore\")", code: true },
    { t: " turns an unseen category into an all-zero block rather than raising. The deployed application therefore degrades gracefully instead of crashing, and still returns a prediction for human review. A test scores a record containing an invented payment method and contract type to confirm this." },
  ]),
  h2("4.4 Feature engineering"),
  p("Seven interpretable features were constructed and evaluated: average realised monthly spend, a charges trend ratio, counts of services and protective add-ons, tenure bands, a new-customer flag and a no-protection flag. Section 7.6 reports the outcome, which was that they did not earn their place."),
  pageBreak()
);

// ============================== 5. MODELS ==================================
children.push(
  h1("5. Models Trained and Performance Comparison"),
  h2("5.1 Models compared"),
  table(
    ["Model", "Role", "Configuration"],
    [
      ["Logistic Regression", "Candidate", "max_iter=2000, class_weight=\"balanced\", with median imputation, standard scaling and one-hot encoding"],
      ["Random Forest", "Candidate", "400 trees, min_samples_leaf=5, class_weight=\"balanced\", with median imputation and one-hot encoding"],
      ["Dummy (stratified)", "Reference only", "Never eligible for selection; exists to make the accuracy argument concrete"],
    ],
    [22, 16, 62]
  ),
  spacer(),
  p("The two candidates are deliberately complementary — a regularised linear model and a bagged tree ensemble — both explainable and both available without adding a dependency. Gradient-boosting libraries were considered and rejected: they add a compiled dependency to the deployment image, and the marginal gain would not change any conclusion in this report."),
  h2("5.2 Evaluation metrics and why they were chosen"),
  table(
    ["Metric", "Why it matters here"],
    [
      ["Recall", "The share of actual churners identified. A miss means no review happens at all — the costly, silent error."],
      ["Precision", "The share of flagged accounts that really churn. Governs wasted specialist time."],
      ["F1", "Balances the two on the minority class."],
      ["ROC-AUC", "Threshold-independent ranking quality — the right measure for a prioritisation tool."],
      ["Accuracy", "Reported for completeness, but insufficient alone on a 26.54% positive rate."],
    ],
    [18, 82]
  ),
  spacer(),
  h2("5.3 Cross-validated comparison"),
  ...figure(F("14_cv_model_comparison.png"), "Cross-validated model comparison, five-fold stratified, on the training split only.", 460),
  h2("5.4 Full performance comparison"),
  p("Cross-validation columns are computed on the training split only. Test columns come from the held-out 20% that no model saw during fitting or selection."),
  table(
    ["Model", "CV ROC-AUC", "CV F1", "CV recall", "Test ROC-AUC", "Test F1", "Test recall", "Test precision", "Test accuracy"],
    [
      ["Logistic Regression (selected)", "0.8460", "0.6286", "0.8013", "0.8414", "0.6130", "0.7834", "0.5034", "0.7374"],
      ["Random Forest", "0.8454", "0.6296", "0.7632", "0.8417", "0.6349", "0.7834", "0.5337", "0.7608"],
      ["Dummy (stratified)", "0.5065", "0.2762", "0.2776", "0.5163", "0.2903", "0.2914", "0.2891", "0.6217"],
    ],
    [26, 11, 9, 10, 11, 9, 10, 10, 10],
    ["l", "r", "r", "r", "r", "r", "r", "r", "r"]
  ),
  spacer(),
  ...figure(F("13_roc_curves.png"), "ROC curves on the held-out test set. Both candidates reach approximately 0.841 AUC; the stratified baseline sits on the diagonal.", 430),
  h2("5.5 Why accuracy alone would have been misleading"),
  p([
    { t: "The stratified baseline makes this concrete rather than rhetorical. It achieves " },
    { t: "62.17% accuracy", b: true },
    { t: " while finding almost no churners: recall 0.2914 and ROC-AUC 0.5163, which is no better than chance at ranking. An accuracy-led selection would have rated it as respectable." },
  ]),
  h2("5.6 Confusion matrix of the selected model"),
  ...figure(F("12_confusion_matrix_logistic_regression.png"), "Confusion matrix for the selected model on the held-out test set of 1,409 customers.", 400),
  table(
    ["", "Predicted: retained", "Predicted: churn"],
    [["Actual: retained", "746 (true negative)", "289 (false positive)"], ["Actual: churn", "81 (false negative)", "293 (true positive)"]],
    [34, 33, 33]
  ),
  spacer(),
  h2("5.7 What the errors mean commercially"),
  bullet([{ t: "81 false negatives of 374 actual churners (21.7%). ", b: true }, { t: "These customers churned but were never flagged. No retention review happens, so the opportunity is lost silently. This is the costly error and the reason recall is weighted." }]),
  bullet([{ t: "289 false positives of 582 flagged accounts (49.7%). ", b: true }, { t: "These customers would have stayed. The cost is specialist time and the risk of an unnecessary contact — recoverable." }]),
  bullet([{ t: "582 of 1,409 customers flagged (41.3%). ", b: true }, { t: "The review workload is bounded and plannable." }]),
  pageBreak()
);

// ============================== 6. SELECTION ===============================
children.push(
  h1("6. Justification for the Selected Model"),
  h2("6.1 The selection rule, fixed in code before any test result existed"),
  p("The rule below was written into src/train.py as executable code before the test set was scored. This is what makes the held-out evaluation unbiased: a rule chosen after seeing test numbers is not a rule."),
  code([
    "1. Compare candidates by mean ROC-AUC under stratified 5-fold",
    "   cross-validation on the TRAINING SPLIT ONLY.",
    "2. If the two means differ by less than 0.01, break the tie on mean CV F1.",
    "3. If that gap is also under 0.01, break the tie on mean CV recall,",
    "   because a missed churner costs more than an unnecessary review.",
    "4. Score the held-out test set ONCE, after selection, for reporting only.",
  ]),
  h2("6.2 What the rule actually did"),
  p("The two candidates were effectively tied. Cross-validated ROC-AUC differed by 0.0005 (0.8460 against 0.8454) and F1 by 0.0010 (0.6286 against 0.6296). Both gaps fell inside the 0.01 tolerance, so the rule fell through to cross-validated recall, where Logistic Regression led 0.8013 to 0.7632."),
  p([{ t: "Logistic Regression was therefore selected.", b: true }]),
  h2("6.3 An honest note for examination"),
  callout(
    "Stated openly rather than omitted.",
    "On the held-out test set the Random Forest is marginally better on accuracy (0.7608 against 0.7374), precision (0.5337 against 0.5034) and F1 (0.6349 against 0.6130), with identical recall (0.7834) and effectively identical ROC-AUC (0.8417 against 0.8414). The model was not switched. Reselecting after seeing test results would convert the held-out set into a selection set and invalidate every unbiasedness claim in this report. The two models are close enough that either is defensible; what is not defensible is choosing after peeking.",
    "B45309"
  ),
  h2("6.4 Supporting reasons for the linear model"),
  bullet("Its coefficients yield an exact per-prediction contribution decomposition, used in Section 7.4. No approximation is required."),
  bullet("It produces a smaller artifact (8.4 KB) and faster inference, which matters for a container that must start quickly."),
  bullet("It is far easier to defend to a model-risk reviewer than an ensemble of 400 trees."),
  h2("6.5 Saved artifact and reproducibility"),
  table(
    ["Artifact", "Contents"],
    [
      ["model_pipeline.joblib", "The complete pipeline — preprocessing and estimator together, 8.4 KB"],
      ["model_metadata.json", "Model name, version, training timestamp, seed, dataset blob SHA, metrics, confusion matrix, environment versions"],
      ["feature_schema.json", "Predictors, dtypes, observed training categories, numeric bounds, target mapping, UI labels and grouping"],
      ["reference_rates.json", "Descriptive statistics used only for the application's context charts"],
      ["model_card.md", "Intended use, out-of-scope uses, provenance, metrics, limitations, ethics, human-review requirement"],
    ],
    [28, 72]
  ),
  spacer(),
  p([
    { t: "Saving the whole pipeline rather than the estimator alone means the deployed transformation cannot differ from the trained one. The artifact is 8.4 KB, so " },
    { t: "Git LFS is not required", b: true },
    { t: " — this was measured, not assumed. Reproducibility is guaranteed by a fixed seed, pinned dependency versions and the verified dataset SHA; retraining produces byte-identical metrics." },
  ]),
  pageBreak()
);

// ============================== 7. POST-DEPLOYMENT ANALYSIS ================
children.push(
  h1("7. Model Governance Analysis"),
  p("Version 1.1.0 published a list of its own limitations. This section reports the work done to close them, and is the part of the project that goes furthest beyond the brief's minimum."),
  h2("7.1 Fairness audit"),
  p("gender and SeniorCitizen are model predictors, so a subgroup audit was performed on the held-out test set. Three standard criteria were computed. They are mathematically incompatible whenever group base rates differ, so a choice was forced and justified."),
  p([{ t: "This project optimises for equal opportunity", b: true }, { t: " — equal recall across groups — because the harm that matters is an at-risk customer being missed entirely." }]),
  ...figure(F("15_fairness_seniorcitizen.png"), "Fairness criteria by SeniorCitizen on the held-out test set, with group base rates shown for context.", 470),
  table(
    ["Group", "n", "Actual churn rate", "Selection rate", "Recall", "Precision"],
    [
      ["Not senior", "1,187", "0.2325", "0.3614", "0.7319", "0.4709"],
      ["Senior citizen", "222", "0.4414", "0.6892", "0.9286", "0.5948"],
      ["Female", "687", "0.2809", "0.4134", "0.7772", "0.5282"],
      ["Male", "722", "0.2507", "0.4127", "0.7901", "0.4799"],
    ],
    [24, 12, 20, 18, 13, 13], ["l", "r", "r", "r", "r", "r"]
  ),
  spacer(),
  h3("Findings"),
  bullet([{ t: "gender: ", b: true }, { t: "no disparity exceeded the 0.10 materiality convention on any criterion." }]),
  bullet([{ t: "SeniorCitizen: ", b: true }, { t: "material disparity on all four criteria — but the direction matters. Seniors genuinely churn far more (0.4414 against 0.2325), and the model finds at-risk seniors better (recall 0.9286 against 0.7319). On the criterion this project optimises for, the group under-served is non-seniors. The genuine burden on seniors is the false-positive rate (0.5000 against 0.2492): unnecessary contact, not missed reviews." }]),
  h3("The counterfactual that changed the recommendation"),
  p("Rather than argue from principle, the model was retrained with both protected attributes removed and the cost measured:"),
  table(
    ["Metric", "With attributes", "Without", "Cost of removal"],
    [["ROC-AUC", "0.8414", "0.8406", "+0.0008"], ["Recall", "0.7834", "0.7807", "+0.0027"], ["F1", "0.6130", "0.6102", "+0.0028"]],
    [30, 24, 22, 24], ["l", "r", "r", "r"]
  ),
  spacer(),
  callout(
    "Recommendation: remove both attributes before any operational use.",
    "They buy no measurable accuracy — the loss is well inside the ±0.0124 cross-validation standard deviation — while introducing a disparity that must then be explained and defended. They are retained in version 1.1.0 only to preserve the published evidence trail for this submission. A group-specific decision threshold was considered and rejected outright as direct differential treatment by protected characteristic.",
    "B4232B"
  ),
  h2("7.2 Probability calibration"),
  p("The application displays a probability to a decision-maker. A model can rank customers well while its probabilities are systematically wrong, and only calibration justifies presenting a number as though it means what it says."),
  p([{ t: "The outcome was predicted before it was measured. ", b: true }, { t: "Logistic regression is normally well calibrated, but this model uses class_weight=\"balanced\", which deliberately inflates minority-class probabilities to raise recall. It was therefore expected to be over-confident about churn — and it is." }]),
  ...figure(F("16_calibration_curve.png"), "Reliability diagram on the held-out test set, with the distribution of predicted probabilities beneath.", 430),
  table(
    ["Variant", "Brier", "ECE", "MCE", "ROC-AUC", "Mean predicted"],
    [
      ["Deployed (uncalibrated)", "0.1688", "0.1503", "0.3163", "0.8414", "0.4157"],
      ["Isotonic", "0.1388", "0.0194", "0.1974", "0.8413", "0.2671"],
      ["Sigmoid", "0.1383", "0.0254", "0.1410", "0.8416", "0.2678"],
    ],
    [30, 14, 14, 14, 14, 14], ["l", "r", "r", "r", "r", "r"]
  ),
  spacer(),
  p("The observed base rate is 0.2654 against a mean prediction of 0.4157 — the model overstates churn probability by roughly 0.15. Isotonic calibration reduces Expected Calibration Error from 0.1503 to 0.0194 while leaving ROC-AUC unchanged at 0.8413, confirming that calibration changes what the number means, not who is ranked highest. The application states on screen that its probabilities are model scores rather than validated frequencies."),
  h2("7.3 Decision threshold"),
  p("Version 1.1.0 used a threshold of 0.50 and documented it honestly as a default rather than an optimum. The cost-optimal threshold depends entirely on one business quantity — how many unnecessary reviews one missed churner is worth — which was never supplied. Inventing a currency figure would have been fabricating a business claim, so the whole sensitivity curve is published instead."),
  ...figure(F("17_threshold_analysis.png"), "Threshold trade-off, and the cost-minimising threshold as a function of the miss-to-review cost ratio.", 490),
  table(
    ["Cost ratio", "Optimal threshold", "Recall", "Precision", "Customers flagged"],
    [
      ["1:1", "0.73", "0.5695", "0.6574", "324 (23.0%)"],
      ["3:1", "0.44", "0.8422", "0.4817", "654 (46.4%)"],
      ["5:1", "0.33", "0.9171", "0.4403", "779 (55.3%)"],
      ["10:1", "0.18", "0.9733", "0.3828", "951 (67.5%)"],
      ["20:1", "0.12", "0.9866", "0.3545", "1,041 (73.9%)"],
    ],
    [18, 22, 16, 18, 26], ["r", "r", "r", "r", "r"]
  ),
  spacer(),
  p([
    { t: "The deployed 0.50 threshold is cost-optimal at a ratio of roughly ", },
    { t: "3:1", b: true },
    { t: ". Using it was always an implicit assertion about relative costs; that assertion is now explicit. The application exposes the threshold as an adjustable control so the sensitivity is visible to the user rather than buried in a report." },
  ]),
  h2("7.4 Per-prediction explainability"),
  p([
    { t: "For a linear model, each feature's contribution to the log-odds is exactly its coefficient multiplied by its transformed value. This is " },
    { t: "not an approximation of the model — it is the model", b: true },
    { t: ", and the contributions plus the intercept reconstruct the score exactly. A test asserts that reconstruction to floating-point precision across 25 real customers on every run. SHAP was considered and rejected: it would estimate, at the cost of a heavy dependency, a quantity available here in closed form." },
  ]),
  h2("7.5 Drift detection"),
  callout(
    "What this is, and what it is not.",
    "The dataset is a single cross-section with no time dimension, so no real drift can be observed and none is claimed. What has been built is the apparatus — a persisted baseline profile and two detectors — together with a demonstration that it works.",
    "1E40AF"
  ),
  ...figure(F("18_drift_detection.png"), "Drift detection on a simulated acquisition campaign. The detector reports ALERT on shifted data and STABLE on the unshifted holdout.", 470),
  p([
    { t: "The detector is validated in " },
    { t: "both directions", b: true },
    { t: ", which matters: a detector that always fires is as useless as one that never does. On the unshifted held-out set it flags 0 of 19 features and reports STABLE. On a deliberately shifted sample — mostly new month-to-month fibre customers, as an acquisition campaign would produce — it flags 15 of 19 with 7 at alert level and reports ALERT." },
  ]),
  h2("7.6 Feature engineering and hyperparameter search"),
  p("Seven interpretable features were engineered and both models were grid-searched. Four arms were compared by cross-validation on the training split, so the contribution of each change is separable rather than confounded."),
  ...figure(F("19_tuning_experiment.png"), "Four-arm comparison of feature engineering and hyperparameter search, cross-validated on the training split only.", 490),
  table(
    ["Arm", "Features", "Hyperparameters", "Best CV ROC-AUC"],
    [
      ["A", "Raw 19", "Hand-set (deployed)", "0.8460"],
      ["B", "Raw 19", "Grid-searched", "0.8481"],
      ["C", "Raw + 7 engineered", "Hand-set", "0.8468"],
      ["D", "Raw + 7 engineered", "Grid-searched", "0.8476"],
    ],
    [10, 34, 34, 22], ["l", "l", "l", "r"]
  ),
  spacer(),
  callout(
    "Outcome: not adopted.",
    "The best arm gained +0.0022 mean CV ROC-AUC against an adoption bar of 0.005 that was fixed before the results were read — less than half the bar, and well inside the ±0.0124 cross-validation standard deviation. The deployed model is unchanged. This is a result rather than a failure: it says the signal in this dataset is largely exhausted by the raw features and sensible defaults. Adopting a difference indistinguishable from noise would have added a permanent second transformation to keep consistent between training and serving, for nothing.",
    "15803D"
  ),
  pageBreak()
);

// ============================== 8. APPLICATION =============================
children.push(
  h1("8. The Working Application"),
  h2("8.1 Design principles"),
  bullet("Artifacts are loaded once per process with st.cache_resource, using paths resolved relative to the application file. The application never trains anything at startup."),
  bullet("Every control is built from feature_schema.json, so the deployed form cannot drift away from the trained pipeline."),
  bullet("A token-based design system provides light and dark themes with an in-app toggle. The charts consume the same tokens, so they follow the theme rather than remaining light-mode islands."),
  bullet("No external font, stylesheet or script is referenced. The page is entirely self-contained, which removes a supply-chain and privacy surface."),
  bullet("Errors show a user-safe message containing no path, stack frame or internal identifier; the technical detail goes to the server log."),
  h2("8.2 Application home screen"),
  ...figure(S("app-space-01-home.png"), "The deployed application at https://krish21may-churn.hf.space, showing the business purpose, model and version badges, the fictional-data disclaimer, and measured held-out performance.", 560),
  h2("8.3 Input form and logical dependencies"),
  p("Controls are provided for all nineteen predictors, grouped into customer profile, services, contract and billing, and charges and tenure. Logical dependencies are enforced so the form cannot produce a combination the model never saw: with no phone service, MultipleLines locks to \"No phone service\"; with no internet service, every internet add-on locks to \"No internet service\"."),
  h2("8.4 A completed assessment"),
  ...figure(S("app-space-02-assessment.png"), "A completed assessment on the live Space. The result card shows the probability, risk band, predicted class, decision threshold, model version and a cautiously worded suggested review action.", 560),
  p([
    { t: "The same input returns " },
    { t: "22.9%", b: true },
    { t: " in the local Python environment, the local Docker container and the deployed Space. This cross-environment agreement is the practical justification for pinning scikit-learn to the exact training version." },
  ]),
  h2("8.5 Per-prediction contribution analysis"),
  ...figure(S("app-space-03-contributions.png"), "The contribution breakdown on the live Space, showing which attributes moved the score and in which direction, with the causal-language disclaimer in the chart title.", 560),
  p("The chart is titled \"What moved this model's score (association within the training sample, not causes)\". The wording is deliberate: the interface must never imply that changing an attribute would change the customer's behaviour."),
  h2("8.6 Batch scoring and the retention work queue"),
  ...figure(S("app-space-05-batch.png"), "The batch scoring tab, which turns an uploaded customer file into a ranked retention work queue with a CSV export.", 560),
  p("A customer CSV is validated against the feature schema before any scoring begins, so a malformed file produces per-column errors rather than a partial result that someone might trust. One thousand customers are scored and ranked in 0.01 seconds. Uploaded data is scored in memory and never written to disk."),
  h2("8.7 Local testing performed"),
  bullet("All dependencies installed into a Python 3.11 virtual environment matching the container runtime."),
  bullet("The application run locally and exercised with both documented demonstration profiles and with manual input combinations."),
  bullet("Both themes verified in a browser, including the locked-dependency behaviour and the adjustable threshold."),
  bullet("A Streamlit smoke test in the release gate starts the real server and requires HTTP 200 from its health endpoint."),
  bullet("The Docker image built and run locally, confirmed to answer its health check and to reproduce the local prediction exactly."),
  pageBreak()
);

// ============================== 9. REPOSITORY ==============================
children.push(
  h1("9. GitHub Repository Structure"),
  h2("9.1 Repository"),
  p([{ t: "https://github.com/krish2105/SDAIM-Customer-Churn", b: true, color: NAVY }]),
  ...figure(S("gh-01-repository.png"), "The public GitHub repository containing the complete application, deployment files, tests and documentation.", 560),
  h2("9.2 Structure"),
  p("The brief suggests a minimal structure of app.py, model.joblib, requirements.txt, README.md and .github/workflows/deploy.yml. All five are present. They sit inside a fuller structure that separates training code from the deployment package, because only the deployment package should ever reach the Space."),
  code([
    "SDAIM-Customer-Churn/",
    "├── README.md                    Executive summary, results, links",
    "├── LICENSE_NOTICE.md            Dataset and dependency licensing",
    "├── Makefile                     Every command, runnable from the root",
    "├── requirements-dev.txt         Development and analysis dependencies",
    "├── data/",
    "│   ├── raw/                     Immutable, SHA-verified dataset",
    "│   └── processed/               Reproducible split exports",
    "├── src/                         config, schemas, validation, EDA, train,",
    "│                                evaluate, fairness, calibration, threshold,",
    "│                                drift, tracking, features, tuning",
    "├── notebooks/                   01_eda_and_modeling.ipynb (executed)",
    "├── reports/                     figures, tables and analysis reports",
    "├── deploy/                      <-- everything that ships to the Space",
    "│   ├── app.py                   Streamlit application",
    "│   ├── theme.py                 Design tokens and scoped CSS",
    "│   ├── charts.py                Themed matplotlib charts",
    "│   ├── explain.py               Per-prediction contributions",
    "│   ├── batch.py                 Batch scoring and work queue",
    "│   ├── rationale.py             Guardrailed retention brief",
    "│   ├── Dockerfile               python:3.11-slim, non-root, port 7860",
    "│   ├── requirements.txt         Pinned runtime dependencies",
    "│   ├── README.md                Space configuration (YAML front matter)",
    "│   └── artifacts/",
    "│       ├── model_pipeline.joblib",
    "│       ├── model_metadata.json",
    "│       ├── feature_schema.json",
    "│       ├── reference_rates.json",
    "│       └── model_card.md",
    "├── tests/                       115 automated tests",
    "├── scripts/                     bootstrap, validate, train, test, docker,",
    "│                                secret scan, release verification",
    "├── docs/                        Audit trail and supporting documentation",
    "└── .github/",
    "    └── workflows/",
    "        ├── ci.yml               Validation on every push and pull request",
    "        └── deploy.yml           Automated deployment to the Space",
  ]),
  h2("9.3 The deployment package"),
  ...figure(S("gh-02-deploy-directory.png"), "The deploy/ directory — the only part of the repository synchronised to the Hugging Face Space.", 540),
  p("Keeping the deployment package in its own directory means the training code, the raw dataset, the notebooks, the tests and the reports never enter the container. The image stays small and its attack surface minimal. A test asserts that the application never imports the training package."),
  h2("9.4 Version control practice"),
  ...figure(S("gh-07-commit-history.png"), "Commit history showing incremental development. Each commit was made only after the full test suite and the secret scan passed.", 540),
  p("Before every commit the full test suite and the secret scanner are run, and the staged file list is reviewed. The release-verification script additionally fails if any tracked file matches a credential-bearing filename."),
  pageBreak()
);

// ============================== 10. ACTIONS ================================
children.push(
  h1("10. The GitHub Actions Workflows"),
  p("Two workflows are configured. One validates every change; the other deploys."),
  h2("10.1 Continuous integration — ci.yml"),
  p("Triggered on pull requests and on pushes to main. It performs eight steps:"),
  numbered("Check out the repository, with Git LFS enabled."),
  numbered("Set up Python 3.11, matching the container runtime exactly."),
  numbered("Install the development dependencies."),
  numbered("Validate the raw dataset with --strict-sha, so a missing Git binary fails the build rather than skipping the check."),
  numbered("Compile every source and test file."),
  numbered("Run the full test suite."),
  numbered("Run the secret scanner."),
  numbered("Verify that every required deployment artifact exists and that the Space README declares the Docker SDK on port 7860."),
  h2("10.2 Deployment — deploy.yml"),
  ...figure(S("gh-06-deploy-workflow.png"), "The deployment workflow as published in the repository.", 560),
  p("The workflow is triggered by pushes to main that touch deploy/**, and can also be dispatched manually. Its design reflects several deliberate decisions:"),
  table(
    ["Property", "Value and rationale"],
    [
      ["Validation gate", "A validate job runs the dataset check, the tests and the secret scan. The deploy job declares needs: validate, so a failing test means nothing ships."],
      ["Permissions", "contents: read only — the least privilege the job can operate with."],
      ["Concurrency", "A named concurrency group prevents two deployments from overlapping."],
      ["Configuration check", "HF_SPACE_ID and HF_TOKEN are verified to exist, and the Space ID format is validated, before anything is pushed."],
      ["Credential handling", "The token is read only as ${{ secrets.HF_TOKEN }}. It is never echoed, never interpolated into a URL, and never written to the job summary."],
      ["Sync action", "huggingface/hub-sync@v0.2.1 with repo_type: space, space_sdk: docker and subdirectory: deploy."],
    ],
    [24, 76]
  ),
  spacer(),
  callout(
    "A required input the specification omitted.",
    "The action's published definition was read rather than assumed, which revealed that github_repo_id is a required input. It is supplied as ${{ github.repository }}. Without it the deployment job would have failed at run time.",
    "1E40AF"
  ),
  h2("10.3 Successful workflow execution"),
  ...figure(S("gh-04-ci-run.png"), "Successful continuous-integration run 30019016553. All ten steps completed green.", 560),
  ...figure(S("gh-05-deploy-run.png"), "Successful deployment run. The validate job and the sync job both completed green.", 560),
  ...figure(S("gh-03-actions-list.png"), "The Actions history for the repository, showing repeated successful runs of both workflows.", 560),
  h2("10.4 The guard demonstrated failing before it was demonstrated passing"),
  callout(
    "Stronger evidence than a first-time success.",
    "Before HF_SPACE_ID and HF_TOKEN were configured, deployment run 30019016510 behaved exactly as designed: the validate job passed every step, then the deploy job failed at the configuration check with the message \"Repository variable HF_SPACE_ID is not configured\", and skipped the sync, package-verification and summary steps rather than attempting a push with an empty repository id. The guard was shown to fire, then shown to pass once configured — the same standard applied to the secret scanner, which was verified against synthetic credentials.",
    "15803D"
  ),
  pageBreak()
);

// ============================== 11. DEPLOYMENT =============================
children.push(
  h1("11. Deployment on Hugging Face"),
  h2("11.1 The Space"),
  p([{ t: "https://huggingface.co/spaces/krish21may/churn", b: true, color: NAVY }]),
  ...figure(S("hf-01-space.png"), "The deployed application running publicly on Hugging Face Spaces.", 560),
  h2("11.2 Space configuration"),
  table(
    ["Property", "Value"],
    [
      ["Space ID", "krish21may/churn"],
      ["SDK", "Docker"],
      ["Application port", "7860"],
      ["Visibility", "Public"],
      ["Base image", "python:3.11-slim"],
      ["Runtime user", "Non-root (appuser, uid 1000)"],
      ["Runtime status", "RUNNING"],
    ],
    [34, 66]
  ),
  spacer(),
  ...figure(S("hf-02-space-files.png"), "The files present in the Space, synchronised automatically from the deploy/ directory of the GitHub repository.", 540),
  h2("11.3 The container"),
  p("The Dockerfile creates a non-root application user, installs the pinned runtime dependencies as a separately cached layer, copies only the runtime files and the artifacts, grants the non-root user read access, exposes port 7860 and declares a health check. No credential appears anywhere in the image, and a test asserts that."),
  code([
    "FROM python:3.11-slim",
    "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1",
    "RUN useradd --create-home --uid 1000 appuser",
    "WORKDIR /app",
    "COPY requirements.txt /app/requirements.txt",
    "RUN python -m pip install -r /app/requirements.txt",
    "COPY app.py theme.py charts.py explain.py batch.py rationale.py /app/",
    "COPY artifacts /app/artifacts",
    "USER appuser",
    "EXPOSE 7860",
    "CMD [\"streamlit\", \"run\", \"app.py\", \"--server.address=0.0.0.0\",",
    "     \"--server.port=7860\", \"--server.headless=true\"]",
  ]),
  h2("11.4 Verified deployment evidence"),
  table(
    ["Gate", "Status", "Evidence"],
    [
      ["Repository pushed", "PASS", "Public, 15 commits"],
      ["CI run", "PASS", "Run 30019016553, all ten steps green"],
      ["Deployment run", "PASS", "Run 30020847651, both jobs green"],
      ["Space build", "PASS", "Reached runtime stage RUNNING"],
      ["Live prediction", "PASS", "22.9%, Low risk band"],
      ["Visible-change redeployment", "PASS", "Run 30023117028, version 1.1.0 confirmed live"],
    ],
    [34, 14, 52]
  ),
  spacer(),
  pageBreak()
);

// ============================== 12. AUTOMATION =============================
children.push(
  h1("12. How the Automated Deployment Works"),
  h2("12.1 The chain of events"),
  p("A developer pushes a change to main that touches the deploy/ directory. From that moment nothing is manual:"),
  numbered("GitHub detects the push and evaluates the workflow's path filter. A change confined to documentation or training code does not trigger a deployment."),
  numbered("The validate job checks out the repository, installs dependencies, verifies the dataset against its Git blob SHA, runs the full test suite and scans for credentials."),
  numbered("Only if that job succeeds does the deploy job begin, because it declares needs: validate."),
  numbered("The deploy job verifies that the HF_SPACE_ID repository variable and the HF_TOKEN secret both exist, and that the Space ID has the expected owner/name form. A missing value fails here with an actionable message rather than producing an obscure push error."),
  numbered("It verifies that every required file is present in the deployment package."),
  numbered("The huggingface/hub-sync action authenticates with the token and synchronises the contents of deploy/ into the Space repository."),
  numbered("Hugging Face detects the new commit in the Space and rebuilds the Docker image from the synchronised Dockerfile."),
  numbered("When the build succeeds, the Space restarts and serves the new version on port 7860."),
  h2("12.2 Authentication"),
  p("Authentication uses a fine-grained Hugging Face access token scoped to write to the single target Space and nothing else. It is stored as an encrypted GitHub Actions secret named HF_TOKEN and is never present in the repository, the container image or any log. The Space identifier is stored separately as a repository variable named HF_SPACE_ID, because it is a public identifier rather than a secret and printing it aids diagnosis."),
  callout(
    "A green workflow is not a successful deployment.",
    "The sync step reports that files were transferred. The Space build happens afterwards and can fail on its own. This project therefore treats them as separate claims requiring separate evidence, and the workflow summary says so explicitly rather than implying the deployment succeeded.",
    "B45309"
  ),
  h2("12.3 The visible-change test"),
  p("To prove the automation genuinely works rather than having succeeded once by coincidence, a deliberate visible change was made and traced end to end:"),
  numbered("The application version was raised from 1.0.0 to 1.1.0 in src/config.py."),
  numbered("The model was retrained. The held-out metrics came back identical — ROC-AUC 0.8414, recall 0.7834 — confirming determinism at random_state=42. Only the version and training timestamp changed."),
  numbered("A visible caption was added to the application header, rendered from the artifact metadata rather than hard-coded so it can never disagree with the deployed version."),
  numbered("The tests and the secret scan were run locally, then the change was committed and pushed."),
  numbered("A second deployment run started automatically from the path filter, with no manual dispatch."),
  numbered("The Space rebuilt, and the live application now displays \"Application version 1.1.0 — automated deployment verification\" alongside the version badge."),
  numbered("Predictions were confirmed still working after the redeployment."),
  ...figure(S("app-space-01-home.png"), "The live application showing version 1.1.0 and the automated deployment verification caption, reached with no manual deployment step.", 560),
  p([{ t: "This satisfies Part 4.4 of the brief: a change pushed to main reached the live public application automatically.", b: true }]),
  pageBreak()
);

// ============================== 13. SECURITY ===============================
children.push(
  h1("13. Security and Governance"),
  h2("13.1 Credential handling"),
  table(
    ["Item", "Type", "Location"],
    [
      ["HF_TOKEN", "Encrypted Actions secret", "Repository settings — value never retrievable after creation"],
      ["HF_SPACE_ID", "Repository variable", "Repository settings — a public identifier, deliberately not a secret"],
    ],
    [20, 26, 54]
  ),
  spacer(),
  p("The token is fine-grained and scoped to write to the single target Space. If it leaked, it could affect nothing else in the account."),
  h2("13.2 Secret scanning, and its own verification"),
  p("A scanner runs locally, in continuous integration, and again in the deployment workflow before anything is pushed. It detects Hugging Face tokens, GitHub personal access tokens, AWS access keys, secret keys and session tokens, private-key headers and bearer tokens, and fails on the mere presence of credential-bearing filenames."),
  p([
    { t: "The scanner reports only the file path and the pattern category, never the matched text — a scanner that echoed its findings would leak the secret into continuous-integration logs, which are often more widely readable than the repository itself. " },
    { t: "The scanner was itself verified", b: true },
    { t: " by placing a file containing four synthetic credentials into the project: both the shell scanner and the pytest equivalent correctly failed, then passed again once the file was removed." },
  ]),
  h2("13.3 Container hardening"),
  bullet("Runs as a non-root user created explicitly in the image."),
  bullet("Built from a slim base image containing only the runtime files and artifacts."),
  bullet("No credential is present in any layer, asserted by test."),
  bullet("XSRF protection enabled; usage statistics disabled."),
  bullet("No external resource is fetched at build or request time."),
  h2("13.4 Application-level controls"),
  bullet("No stack trace, filesystem path or internal identifier is ever shown to a user."),
  bullet("Every value rendered into the interface passes through HTML escaping."),
  bullet("No customer data is persisted; batch uploads are scored in memory and discarded."),
  h2("13.5 Governance position"),
  callout(
    "What this model must never do.",
    "It must not autonomously change prices, terminate or modify contracts, deny service, target customers unfairly, or make any financial or customer-treatment decision. Every output requires human review before a customer is contacted. A churn score is a statistical association, not a judgement about a person.",
    "B4232B"
  ),
  h2("13.6 Known security gaps"),
  p("Recorded rather than omitted: there is no automated dependency-vulnerability scanning, no container image scanning, and no signed commits or images. Adding pip-audit and Trivy to the CI job is the recommended next step."),
  pageBreak()
);

// ============================== 14. TESTING ================================
children.push(
  h1("14. Testing and Quality Assurance"),
  h2("14.1 Test suite"),
  table(
    ["Module", "Tests", "What it guards"],
    [
      ["test_data_validation.py", "13", "The dataset contract — schema, counts, domains, blob SHA"],
      ["test_model_artifact.py", "12", "Artifact integrity, metadata realism, fresh-process loading"],
      ["test_prediction.py", "11", "Prediction behaviour, column-order enforcement, determinism"],
      ["test_deployment_files.py", "16", "Deployment configuration, workflow scope, secret hygiene"],
      ["test_analysis.py", "27", "Fairness, calibration, threshold, drift and feature engineering"],
      ["test_app_features.py", "36", "Explainability, batch scoring, retention-brief guardrails"],
      ["Total", "115", "All passing"],
    ],
    [30, 10, 60], ["l", "r", "l"]
  ),
  spacer(),
  h2("14.2 Tests that guard against silent corruption"),
  bullet([{ t: "Column-order enforcement. ", b: true }, { t: "The input columns are reversed and an identical probability is required. Positional rather than name-based selection is a classic silent bug: the pipeline still runs and still returns a plausible number, just a wrong one." }]),
  bullet([{ t: "Contribution reconstruction. ", b: true }, { t: "The explanation must reproduce the model's own score to floating-point precision across 25 real customers. If it ever drifts, the chart is lying and must not be displayed." }]),
  bullet([{ t: "Runtime dependency coverage. ", b: true }, { t: "Each runtime module's abstract syntax tree is parsed and every third-party import checked against the pinned requirements. A hand-maintained list would go stale; this cannot." }]),
  bullet([{ t: "Batch and single-record agreement. ", b: true }, { t: "The two scoring paths must return identical probabilities, or the work queue could disagree with the form." }]),
  bullet([{ t: "Drift detector, both directions. ", b: true }, { t: "It must fire on a shifted sample and stay silent on the unshifted holdout." }]),
  h2("14.3 Quality gates"),
  p("A release-verification script runs ten non-interactive gates and records the actual result of each: dataset validation, syntax compilation, artifact reload in a fresh process, the test suite, a Streamlit smoke test against the real server, the secret scan, required-file verification, the Docker build, a container run with a health check, and a Git staged-file review."),
  p([{ t: "Latest run: 10 PASS, 0 FAIL, 0 NOT RUN.", b: true }]),
  h2("14.4 Defects found and fixed by these gates"),
  p("Recorded because each was a genuine defect that the process caught rather than a rough edge that was tidied:"),
  numbered("The drift detector produced a false positive on the unshifted control set, because an escalation rule let a chi-squared p-value override the Population Stability Index. At n ≈ 1,400 the test flags differences far too small to matter. PSI alone now governs the status, matching what the module's documentation had always said."),
  numbered("The prohibited-language filter in the retention brief matched the word \"causes\" inside its own disclaimer. The pattern now matches assertions of cause rather than the noun, and a test asserts that the fallback text passes the filter it enforces."),
  numbered("A placeholder check matched the word \"actual\" inside the legitimate phrase \"not actual observed commercial customer data\"."),
  numbered("The Streamlit configuration set enableCORS = false alongside enableXsrfProtection = true, a combination Streamlit rejects."),
  numbered("Two feature-engineering tests encoded a wrong expectation — that no engineered feature may be null. AvgMonthlySpend is null for exactly the eleven documented blank-TotalCharges rows, deliberately, so the pipeline's median imputer handles it. The tests were corrected, not the code."),
  pageBreak()
);

// ============================== 15. LIMITATIONS ============================
children.push(
  h1("15. Limitations and Future Work"),
  h2("15.1 Limitations"),
  numbered([{ t: "Fictional data. ", b: true }, { t: "Performance on any live population is unknown and must be revalidated before operational use." }]),
  numbered([{ t: "No time dimension. ", b: true }, { t: "A single cross-section means drift and seasonality cannot be assessed and no monitoring baseline exists." }]),
  numbered([{ t: "Class imbalance limits precision. ", b: true }, { t: "At 0.7834 recall, roughly half the flagged accounts are false positives." }]),
  numbered([{ t: "Probabilities are not calibrated. ", b: true }, { t: "The model overstates churn probability by about 0.15. Ranking is reliable; magnitude is not." }]),
  numbered([{ t: "The threshold is an assumption. ", b: true }, { t: "0.50 is cost-optimal at roughly 3:1, a ratio the business never supplied." }]),
  numbered([{ t: "Protected attributes are retained. ", b: true }, { t: "Removal is recommended and was measured to be nearly free, but was deferred to preserve the published evidence trail." }]),
  numbered([{ t: "Association, never causation. ", b: true }, { t: "The model cannot say what would happen if a customer's contract or services were changed." }]),
  numbered([{ t: "No measured business impact. ", b: true }, { t: "No revenue or churn-reduction effect has been demonstrated." }]),
  h2("15.2 Future work"),
  table(
    ["Initiative", "Why it matters"],
    [
      ["Remove the protected attributes", "Measured to cost +0.0008 ROC-AUC; removes an unforced governance risk"],
      ["Deploy the calibrated model", "Isotonic calibration cuts ECE from 0.1503 to 0.0194 at no cost to ranking"],
      ["Obtain the business cost ratio", "One question resolves the threshold entirely"],
      ["FastAPI prediction service", "Decouples the model from the interface so other systems can consume it"],
      ["Database and feature store", "Persists scores and outcomes, enabling a genuine feedback loop"],
      ["Scheduled retraining with gates", "Retrain on a trigger; block promotion on a metric regression"],
      ["Live monitoring and alerting", "Routes drift and performance decay to a real channel"],
      ["A/B evaluation of interventions", "The only route to a substantiated business-value claim"],
      ["Dependency and image scanning", "Closes the known security gap"],
    ],
    [34, 66]
  ),
  spacer(),
  callout(
    "The honest ceiling of the current evidence.",
    "Every claim about business value remains unproven until the A/B evaluation exists. Until a control group has been observed, this platform demonstrates technical feasibility and may support prioritisation for human review. Stating that plainly is a strength of the work, not a hedge.",
    "1E40AF"
  ),
  pageBreak()
);

// ============================== 16. CONCLUSION =============================
children.push(
  h1("16. Conclusion"),
  p("This project delivers a complete, reproducible path from a provenance-verified dataset to an automatically deployed public application. The selected model reaches 0.8414 ROC-AUC and 0.7834 recall on held-out data, identifying 293 of 374 churners. The application is live, the deployment is automated, and a deliberate visible change was traced from a local commit to the running Space with no manual step."),
  p("What we would emphasise as much as the metrics is the discipline around them. The selection rule was written before the test set was examined. The fairness audit was accompanied by a counterfactual that changed its own recommendation. The calibration outcome was predicted before it was measured. The drift detector was validated in both directions. Feature engineering and hyperparameter search were carried out, measured, and then rejected on the evidence because the gain did not clear a bar set in advance."),
  p([{ t: "Equally important is what this platform does not do. ", b: true }, { t: "It makes no financial claim, automates no customer-treatment decision, and states its limitations in the application itself as well as in this report — including the ones that remain open. It demonstrates technical feasibility and may support prioritisation for human review. That is the honest extent of what the evidence supports." }]),
  spacer(300),
  h1("17. References"),
  numbered("IBM. Telco Customer Churn sample. https://github.com/IBM/telco-customer-churn-on-icp4d (Apache-2.0)."),
  numbered("IBM Documentation. Samples: Telco customer churn. https://www.ibm.com/docs/en/cognos-analytics"),
  numbered("Pedregosa, F. et al. (2011). Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, 2825–2830."),
  numbered("Mitchell, M. et al. (2019). Model Cards for Model Reporting. Proceedings of FAT* '19, 220–229."),
  numbered("Streamlit documentation. https://docs.streamlit.io"),
  numbered("Hugging Face. Spaces — Docker SDK. https://huggingface.co/docs/hub/spaces-sdks-docker"),
  numbered("GitHub. GitHub Actions documentation. https://docs.github.com/actions"),
  numbered("Hugging Face. hub-sync action. https://github.com/huggingface/hub-sync"),
  numbered("W3C. Web Content Accessibility Guidelines (WCAG) 2.1. https://www.w3.org/TR/WCAG21/"),
  spacer(300),
  h1("18. Team Contributions"),
  table(
    ["Member", "Student ID", "Primary contribution"],
    [
      ["Krishna Mathur", "AS25DXB018", "Platform, Docker packaging, CI/CD workflows, security controls and deployment"],
      ["Yash Petkar", "AS25DXB021", "Modelling rigour — fairness audit, calibration analysis, experiment tracking and registry"],
      ["Atharva Soundankar", "AS25DXB020", "Application development, explainability, threshold analysis, batch scoring and drift detection"],
    ],
    [24, 18, 58]
  ),
  spacer(),
  p("All three members contributed to the exploratory analysis, the report, the evidence pack and the demonstration."),
  spacer(400),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    border: { top: { style: BorderStyle.SINGLE, size: 6, color: RULE, space: 12 } },
    children: [new TextRun({
      text: "Customer Churn Intelligence and Retention Decision-Support Platform · Version 1.1.0",
      size: 17, color: MUTED, italics: true,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({
      text: "github.com/krish2105/SDAIM-Customer-Churn  ·  huggingface.co/spaces/krish21may/churn",
      size: 17, color: NAVY,
    })],
  })
);

// ===========================================================================

const doc = new Document({
  creator: "Krishna Mathur, Yash Petkar, Atharva Soundankar",
  title: "Customer Churn Intelligence and Retention Decision-Support Platform",
  description: "SDAIM Term 3 final project report",
  numbering: {
    config: [
      {
        reference: "bullets",
        levels: [
          { level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 460, hanging: 260 } } } },
          { level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 900, hanging: 260 } } } },
        ],
      },
      {
        reference: "numbers",
        levels: [
          { level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 460, hanging: 260 } } } },
        ],
      },
    ],
  },
  styles: {
    default: {
      document: { run: { font: "Calibri", size: 21, color: INK } },
    },
  },
  sections: [
    {
      properties: {
        page: {
          size: { width: PAGE_W, height: PAGE_H },
          margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN },
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: RULE, space: 4 } },
              tabStops: [{ type: TabStopType.RIGHT, position: 9360 }],
              children: [
                new TextRun({ text: "Customer Churn Intelligence", size: 16, color: MUTED }),
                new TextRun({ text: "\tSDAIM Term 3 — Final Project Report", size: 16, color: MUTED }),
              ],
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: "Page ", size: 16, color: MUTED }),
                new TextRun({ children: [PageNumber.CURRENT], size: 16, color: MUTED }),
                new TextRun({ text: " of ", size: 16, color: MUTED }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: MUTED }),
              ],
            }),
          ],
        }),
      },
      children,
    },
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync(OUT, buffer);
  const kb = Math.round(buffer.length / 1024);
  console.log(`Wrote ${OUT}`);
  console.log(`${kb} KB · ${figureCounter} figures · ${children.length} blocks`);
});
